name: design_system
description: Design tokens, theme and base components for Banca Digital.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins-semibold.ttf
          weight: 600
    - family: Open Sans
      fonts:
        - asset: assets/fonts/open-sans-regular.ttf
          weight: 400
        - asset: assets/fonts/open-sans-semibold.ttf
          weight: 600
